name: "qd"



on:
  workflow_dispatch:
  watch: 
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)
        
      - name: Install dependencies
        env:

          PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
        run: |


          python -m pip install --upgrade pip
          pip install selenium
          pip install lxml
          wget https://download-ssl.firefox.com.cn/releases/firefox/esr/91.0/zh-CN/Firefox-latest-x86_64.tar.bz2
          bunzip2 -d Firefox-latest-x86_64.tar.bz2
          tar -xvf Firefox-latest-x86_64.tar
          wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
          tar -zxvf geckodriver-v0.29.1-linux64.tar.gz
          cp geckodriver /usr/local/bin/

          python qd.py
