name: "qd"



on:
  workflow_dispatch:
  watch: 
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)
        
      - name: Install dependencies
        env:

          PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
        run: |

          yum install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
          yum install mesa-libOSMesa-devel gnu-free-sans-fonts wqy-zenhei-fonts
          wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          mv chromedriver /usr/bin/
          chmod +x /usr/bin/chromedriver
          
          python -m pip install --upgrade pip
          pip install selenium
          pip install lxml


          python qd.py
