name: "qd"



on:
  workflow_dispatch:
  watch: 
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)
        
      - name: Install dependencies
        env:

          PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
        run: |
          apt install firefox dbus-x11 xvfb
          sudo Xvfb :10 -ac
          export DISPLAY=:10
          firefox
          cd /tmp
          wget https://github.com/mozilla/geckodriver/releases/download/ V0.18.0/geckodriver-v0.18.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.18.0-linux64.tar.gz 
          cp geckodriver /root/bin
          export PATH=.:/root/bin:$PATH



          
          python -m pip install --upgrade pip
          pip install selenium



          python qd.py
